version = 0.1

[default.build.parameters]
template = "sam-template.yaml"

[default.deploy.parameters]
template = ".aws-sam/build/template.yaml"
stack_name = "klients-voice"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
confirm_changeset = true
parameter_overrides = "AppBaseUrl=https://klients-voice-dashboard.vercel.app SesFromEmail=soporte@edgardohernandez.com"
